/*
 * This source file was generated by the Gradle 'init' task
 */
package de.infolektuell.gradle.typst

import org.gradle.testfixtures.ProjectBuilder
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertNotNull

/**
 * A simple unit test for the 'org.example.greeting' plugin.
 */
class GradleTypstPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply(GradleTypstPlugin.PLUGIN_NAME)

        // Verify the result
        assertNotNull(project.extensions.findByName("typst"))
    }
}
