/*
 * This source file was generated by the Gradle 'init' task
 */
package de.infolektuell.gradle.typst

import java.io.File
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertTrue
import org.gradle.testkit.runner.GradleRunner
import org.junit.jupiter.api.io.TempDir
import kotlin.io.path.createParentDirectories

/**
 * A simple functional test for the 'org.example.greeting' plugin.
 */
class GradleTypstPluginFunctionalTest {

    @field:TempDir
    lateinit var projectDir: File

    private val buildFile by lazy { projectDir.resolve("build.gradle") }
    private val settingsFile by lazy { projectDir.resolve("settings.gradle") }
    private val typstFile by lazy { projectDir.resolve("src/main/typst/document.typ") }

    @Test fun `can run task`() {
        // Set up the test build
        settingsFile.writeText("")
        buildFile.writeText("""
            plugins {
                id("base")
                id('de.infolektuell.typst')
            }
            typst {
                version = "v0.13.1"
                sourceSets {
                    register("main") {
                        documents.add("document")
                    }
                }
            }
        """.trimIndent())
        typstFile.toPath().createParentDirectories()
        typstFile.writeText("= Test Document\n")

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withProjectDir(projectDir)
        val result = runner.build()
        assertTrue(result.output.contains("SUCCESSFUL"))
    }
}
